######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 3 18:04:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ui
INCLUDEPATH += . ui

# Input
HEADERS += ui/adbUI.h ui/mainUI.h ui/settingsUI.h
SOURCES += main.cpp ui/adbUI.cpp ui/mainUI.cpp ui/settingsUI.cpp
